= J-Voting
:groupId: io.github.j-voting
:artifactId: j-voting
:repository: J-Voting

image:https://travis-ci.com/j-voting/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/j-voting/{repository}"]
image:https://maven-badges.herokuapp.com/maven-central/{groupId}/{artifactId}/badge.svg["Artifact on Maven Central", link="http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22{groupId}%22%20a%3A%22{artifactId}%22"]
image:http://www.javadoc.io/badge/{groupId}/{artifactId}.svg["Javadocs", link="http://www.javadoc.io/doc/{groupId}/{artifactId}"]

A Java project developed during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] M2 MIAGE).

The work was resumed at the end of Version 0.0.2 by a new project team following the Licence 3 MIAGE APP course also given at the University of Paris-Dauphine by Mr CAILLOUX.

The code is hereby published under the MIT License, with their permission.


=== Teams :
===== *SM/PO team* : Théo CHENNEBAULT
.*Tasks*
* Format files
* Pass to JUnit 5
* Debug import SWT package for OSX and Windows
* Pass to parent pom oliviercailloux
* Nouveau groupid
* Rework the Overide of toString(), equals() and hashCode()

===== *Team 1* : Anael Dray / Emilie Chhean
.*Tasks*
* Modify packages names

===== *Team 2* : Mattéo Loubet / Louis Ledoux
.*Tasks*
* Eclipse Warnings suppression

===== *All Teams*
.*Tasks*
* Setup Eclipse environment : Formatter, Sonarlint
